### ISSUE TITLE
Names with ï fail the regex test

### ISSUE THREAD

**Issue by Wardergrip** [avadae/subcheck#3]
My name has "ï" in it and this means that my file would include this symbol. The regex to check the file name is as follows:
`[1,2,3]DAE[0,1,2]\d_Programming4_[0,1]\d_[a-zA-Z]+_[a-zA-Z]+(-\d)?\.zip$`

This means that my name automatically fails the regex because it fails the `[a-zA-Z]` part.

A better (and more correct) way to check for names would be to check for non whitespace charachters
`[1,2,3]DAE[0,1,2]\d_Programming4_[0,1]\d_\S+_\S+(-\d)?\.zip$`

Quick note that this last regex is mentioned on LEHO but is not present in the latest release at the time of writing (v1.1.1)

Credits: @BramVernimmen

**Comment by Wardergrip** [comment]
[config.txt](https://github.com/avadae/subcheck/files/10849003/config.txt)

This file was made after subcheck was run, this shows the regex used once more.

**Comment by avadae** [comment]
The regex is correct, I do not wish to accept filenames containing non-ascii characters.
https://support.tigertech.net/non-ascii-urls

**Comment by Wardergrip** [comment]
Can the regex on LEHO be updated to prevent confusion? It took me quite some time to figure out what exactly was wrong.

**Comment by avadae** [comment]
That has already been done.
